### ISSUE TITLE
netdiscover not found

### ISSUE THREAD

**Issue by waqarsomra** [MrSuicideParrot/python-netdiscover#1]
i have downloaded the files and installed it python setup.py -- install. it was installed successfully. but when i am trying to discover it gives exception netdiscover not found.
i have passed the path of netdiscover.py in /usr/lib/python2.7/site-packages/netdiscover. 

```
disc = Discover(netdiscover_path="/usr/lib/python2.7/site-packages/netdiscover")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netdiscover/netdiscover.py", line 51, in __init__
    raise Exception("netdiscover not found")
Exception: netdiscover not found
```
i am using python 2.7 in centos 7

**Comment by MrSuicideParrot** [comment]
Do you have the netdiscover installed in your machine? 
By default this library will search for the netdiscover binary in the following paths:
```
    netdiscover
    /usr/bin/netdiscover
    /usr/sbin/netdiscover
    /usr/local/bin/netdiscover
    /sw/bin/netdiscover
    /opt/local/bin/netdiscover
```

**Comment by MrSuicideParrot** [comment]
I think that my Readme doesn't say that it is necessary to install netdiscover to run the library.
 I will add this to the installation procedure.
