### ISSUE TITLE
Output isn`t performing

### ISSUE THREAD

**Issue by DanBrown47** [MrSuicideParrot/python-netdiscover#2]
The parse is not developing any output for the code
from netdiscover import *

if os.geteuid() == 0:
    disc = Discover()

    disc.scan()
else:
    print("Need Root")    

Ran as a superuser

**Comment by MrSuicideParrot** [comment]
I had the same result in my machine. I will try to identify and solve the problem and then I will follow-up with you.

**Comment by MrSuicideParrot** [comment]
Your program comes to an end or stalls? 
You are running netdiscover without a target subnet, which means that it will scan all private subnets. Scanning all private networks will take a long time. 
Nevertheless, the code you send me doesn't print the result from `disc.scan()`.  `disc.scan` returns an array with the results and doesn't print by itself. In the examples, I'm using ipython shell which prints automatically the return of a function.

**Comment by DanBrown47** [comment]
Hi, I have tried the `disc.scan` The Output it gives is

`<bound method Discover.scan of <netdiscover.netdiscover.Discover object at 0x7f929f8b8b80>>`

Also How to specify subnet?

I have used a python3 shell. Ran as root

**Comment by MrSuicideParrot** [comment]
To specify a subnetwork you can call the scan function like with the option `ip_range`, like this disc.scan(ip_range="192.168.1.0/24").

If you don't see any host in your scan, it's also possible to be a known bug of netdiscover: https://forums.kali.org/archive/index.php/t-45949.html
