### ISSUE TITLE
Allow parse_output to add vendor to result dict

### ISSUE THREAD

**Issue by Bouni** [MrSuicideParrot/python-netdiscover#6]
I would like to have the vendor as part of the result. Would you accept a PR that enables that (maybe optionally)

**Comment by MrSuicideParrot** [comment]
I will accept the PR. During the weekend I'll check  and test your pull request.

**Comment by Bouni** [comment]
Thanks, highly appreciate it!

**Comment by Bouni** [comment]
Hey @MrSuicideParrot any news on this?

**Comment by MrSuicideParrot** [comment]
Sorry for the delay, but I completely forgot about this pr.
I have accepted it and created a new release with the new feature.
Thank you very much for your contribution!!
